// ============================================================
// MANIFEST — auto-generated by scripts/generate_manifest.py
// Run `python scripts/generate_manifest.py` to rebuild from the reports/ folder.
const REPORT_MANIFEST = [
  { folder: "RKLB_20260521_171356", ticker: "RKLB", ts: "2026-05-21 17:13", company: "Rocket Lab Corporation" },
  { folder: "NOW_20260521_103841", ticker: "NOW", ts: "2026-05-21 10:38", company: "ServiceNow, Inc." },
  { folder: "NBIS_20260521_135932", ticker: "NBIS", ts: "2026-05-21 13:59", company: "Nebius Group N.V." },
  { folder: "MSFT_20260519_215050", ticker: "MSFT", ts: "2026-05-19 21:50", company: "Microsoft Corporation" },
  { folder: "LUNR_20260521_173142", ticker: "LUNR", ts: "2026-05-21 17:31", company: "Intuitive Machines, Inc." },
  { folder: "IREN_20260521_134807", ticker: "IREN", ts: "2026-05-21 13:48", company: "IREN Limited" },
];
// ============================================================ END MANIFEST

// Stages used in the detail view
const STAGES = [
  { id: "1_analysts",  label: "AI Agents",      files: ["market", "sentiment", "news", "fundamentals"] },
  { id: "2_research",  label: "Research Debate", files: ["bull", "bear", "manager"] },
  { id: "3_trading",   label: "Trader",          files: ["trader"] },
  { id: "4_risk",      label: "Risk Committee",  files: ["aggressive", "neutral", "conservative"] },
  { id: "5_portfolio", label: "Portfolio Mgr",   files: ["decision"] },
];

// Parse a "**Field**: value\n\n**Field2**: value2" block of pseudo-frontmatter
function parseFieldedMarkdown(text) {
  const out = {};
  if (!text) return out;
  const re = /\*\*([^*]+)\*\*:\s*([\s\S]*?)(?=\n\n\*\*[^*]+\*\*:|\nFINAL TRANSACTION PROPOSAL|$)/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    const key = m[1].trim();
    const val = m[2].trim();
    out[key] = val;
  }
  const finalProp = text.match(/FINAL TRANSACTION PROPOSAL:\s*\*\*([A-Z]+)\*\*/);
  if (finalProp) out["__final"] = finalProp[1];
  return out;
}

// Cache for fetched text
const fetchCache = new Map();
async function fetchText(path) {
  if (fetchCache.has(path)) return fetchCache.get(path);
  try {
    const r = await fetch(path);
    if (!r.ok) throw new Error(r.status);
    const raw = await r.text();
    const t = raw.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
    fetchCache.set(path, t);
    return t;
  } catch (e) {
    fetchCache.set(path, null);
    return null;
  }
}

// Fetch + parse a full report
async function loadReport(folder) {
  const base = `reports/${folder}`;
  const tasks = [];
  const docs = {};

  for (const stage of STAGES) {
    docs[stage.id] = {};
    for (const f of stage.files) {
      const p = `${base}/${stage.id}/${f}.md`;
      tasks.push(fetchText(p).then(t => { docs[stage.id][f] = t; }));
    }
  }

  let meta = {};
  tasks.push(fetchText(`${base}/meta.json`).then(t => {
    if (t) { try { meta = JSON.parse(t); } catch (e) {} }
  }));

  await Promise.all(tasks);

  const decisionFields = parseFieldedMarkdown(docs["5_portfolio"]?.decision || "");
  const traderFields   = parseFieldedMarkdown(docs["3_trading"]?.trader || "");
  const researchFields = parseFieldedMarkdown(docs["2_research"]?.manager || "");

  return { folder, docs, decision: decisionFields, trader: traderFields, research: researchFields, meta };
}

// Verdict normalization
function normalizeVerdict(rating, finalProp) {
  const r = (rating || "").toLowerCase();
  const f = (finalProp || "").toUpperCase();
  if (f === "SELL" || r.includes("sell") || r.includes("underweight")) return { kind: "SELL", label: rating || "Sell" };
  if (f === "BUY"  || r.includes("buy")  || r.includes("overweight"))  return { kind: "BUY",  label: rating || "Buy" };
  return { kind: "HOLD", label: rating || "Hold" };
}

// Confidence heuristic — synthesized from convergence cues in the manager's thesis
function confidenceFromReport(report) {
  const real = parseFloat(report.decision["Confidence"]);
  if (!isNaN(real)) return Math.max(0, Math.min(1, real));
  // existing heuristic fallback:
  const v = normalizeVerdict(report.decision.Rating, report.trader.__final);
  let score = 0.55;
  const thesis = (report.decision["Investment Thesis"] || "").toLowerCase();
  if (thesis.includes("converged") || thesis.includes("consensus")) score += 0.20;
  if (thesis.includes("decisive") || thesis.includes("clear")) score += 0.10;
  if (thesis.includes("uncertain") || thesis.includes("unresolved")) score -= 0.08;
  if (v.kind === "HOLD") score -= 0.05;
  if (report.trader.__final && report.trader.__final !== "HOLD") score += 0.05;
  return Math.max(0.35, Math.min(0.95, score));
}

// Extract dollar/number values
function num(v) {
  if (v == null) return null;
  const m = String(v).match(/-?\$?\s?(\d+(?:[.,]\d+)*)/);
  return m ? parseFloat(m[1].replace(/,/g, "")) : null;
}

Object.assign(window, {
  REPORT_MANIFEST,
  STAGES,
  loadReport,
  parseFieldedMarkdown,
  normalizeVerdict,
  confidenceFromReport,
  num,
  fetchText,
});

// Tweaks context
window.TweaksContext = React.createContext({
  accent: "#4F5AE6",
  density: "cozy",
  heroSize: "large",
  showConfidence: true,
  showBullBear: true,
  highlightMetrics: true,
});
